### ISSUE TITLE
License link not working

### ISSUE THREAD

**Issue by CostantinB** [codeforamerica/councilmatic#44]
Hi!

Under the read me file when I click on license the link (https://github.com/cfalabs/open311/blob/master/LICENSE.mkd) is not working..

Under what license you have published the code?

Thanks,
Costantin

**Comment by MatthewLoveless** [comment]
Here is an updated link to the license: https://github.com/codeforamerica/open311/blob/master/LICENSE.md

**Comment by mjumbewu** [comment]
@CostantinB thanks for pointing this out, and thanks @MatthewLoveless for updating the link.
